apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eloquia-dev-api
spec:
  secretName: eloquia-dev-api-tls
  issuerRef:
    name: letsencrypt-staging # <to be changed later if necessary>
    kind: ClusterIssuer
  dnsNames:
    - api.dev.eloquia.bajaga.net
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eloquia-dev-portal
spec:
  secretName: eloquia-dev-portal-tls
  issuerRef:
    name: letsencrypt-staging # <to be changed later if necessary>
    kind: ClusterIssuer
  dnsNames:
    - portal.dev.eloquia.bajaga.net
