apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:NMzQg1QVMw6W0Qgl,iv:cvyeOlwyFvVe7tPZfeEi+W7swdYZMNrM9Wh3aEOMNHY=,tag:P5hdKl6BtTVM/jKP1Pp11A==,type:str]
    postgres-password: ENC[AES256_GCM,data:2hN9HUDTwDLUolBq,iv:VIf5MAWmdiKj+4diT5Pvb+2WKbbZrKM9LGuPmQSntSc=,tag:51KIwZFbkqTqS/sADxKn2g==,type:str]
sops:
    age:
        - recipient: age1ygxhg6wss8r0vm83cc557x9cxlx24m74ma4xh26lwspw7v0lgvzq5lddn0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cXR3UUFSVStQa2N2dXNw
            S1kyR1FCYnpSUmhYUUZLODFVVTVvUnhpNURrCmhOcG5uOGdKMHRpR3dNZkRKWEZG
            WGZFQ05rM1BvUkNJQ3JGaHhvMVJoNjgKLS0tIFdOQzB1dHhvZGIyUStqN095MXJa
            bFNGazA1Q28waVIxZVBDSzJrelQwdzQKYyfLsdILlVB8A9HUPo+Bq9fKxUB7IXgx
            2lUaPSiA8Cz9ICd5+5J9P0z5xoALj9Lutcj6siXVjklFdEKWMX+KQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T21:04:22Z"
    mac: ENC[AES256_GCM,data:BD4dbwQ8GodGCnB15oc+pEf43rmW+kzEanxZt8rLbj8JsnP/RQO5pcEbD2K5e2EtfDJwhIGAtbm4PszUG1NFW3tASEZjHpwAY1XX5cvCfUvly0xzgMHMPliSowKaqBnZKgeidH1XkuZVWxd0ugKrSg3tAV2UOXoyqIkLJRSgWIs=,iv:kF+TCAaCoRyWoNvGCL4wU6U0V13BdMjOrz3EtvgzP64=,tag:o9vXf8jj1j9wufW9+hXjYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:3kgG2dWkptmb82fHWerguSlt497OKziJaAM787BM7rXPE5FiQWwJPODEP4kqGW+5pF/iJ490jl1JU+uSokdq/aC03B0qqj0hhX5oU3gCOu4ACEuMrb3BHA==,iv:hnIgx3p7lEZdrD8Zs60ESkwZaXNuKfVtVq+OqdxcNlw=,tag:mvKkBuDTeFDWoJb8rN+V5g==,type:str]
    AUTH_COOKIE_SECRET: ENC[AES256_GCM,data:2VR13ju/bXUQnw==,iv:ZeMSU1awRWBqlzjniXprMS6NXVaPInqLJk57mBVqDWY=,tag:GrRO5FBhPKrEXuHK/Abpzw==,type:str]
sops:
    age:
        - recipient: age1ygxhg6wss8r0vm83cc557x9cxlx24m74ma4xh26lwspw7v0lgvzq5lddn0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cXR3UUFSVStQa2N2dXNw
            S1kyR1FCYnpSUmhYUUZLODFVVTVvUnhpNURrCmhOcG5uOGdKMHRpR3dNZkRKWEZG
            WGZFQ05rM1BvUkNJQ3JGaHhvMVJoNjgKLS0tIFdOQzB1dHhvZGIyUStqN095MXJa
            bFNGazA1Q28waVIxZVBDSzJrelQwdzQKYyfLsdILlVB8A9HUPo+Bq9fKxUB7IXgx
            2lUaPSiA8Cz9ICd5+5J9P0z5xoALj9Lutcj6siXVjklFdEKWMX+KQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T21:04:22Z"
    mac: ENC[AES256_GCM,data:BD4dbwQ8GodGCnB15oc+pEf43rmW+kzEanxZt8rLbj8JsnP/RQO5pcEbD2K5e2EtfDJwhIGAtbm4PszUG1NFW3tASEZjHpwAY1XX5cvCfUvly0xzgMHMPliSowKaqBnZKgeidH1XkuZVWxd0ugKrSg3tAV2UOXoyqIkLJRSgWIs=,iv:kF+TCAaCoRyWoNvGCL4wU6U0V13BdMjOrz3EtvgzP64=,tag:o9vXf8jj1j9wufW9+hXjYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
