apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eloquia-api
spec:
  secretName: eloquia-api-tls
  issuerRef:
    name: letsencrypt-production # <to be changed later if necessary>
    kind: ClusterIssuer
  dnsNames:
    - api.eloquia.bajaga.net
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eloquia-portal
spec:
  secretName: eloquia-portal-tls
  issuerRef:
    name: letsencrypt-production # <to be changed later if necessary>
    kind: ClusterIssuer
  dnsNames:
    - portal.eloquia.bajaga.net
