apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eloquia-production
resources:
  - ../../base/postgres
  - ../../base/backend
  - ../../base/desktop
  - certificates.yaml
  - external-secrets.yaml
patches:
  - target:
      kind: IngressRoute
      name: backend
    path: patches/backend-ingressroute.yaml
  - target:
      kind: IngressRoute
      name: desktop
    path: patches/desktop-ingressroute.yaml
