apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:WIBzwBADigZL1t0d,iv:nQcY8nMBjU6qQjxxeoi7EYkoeI2hgTiuydmyqy+YHM8=,tag:Wc19PdwhL/2KsGT8NgFTXw==,type:str]
    postgres-password: ENC[AES256_GCM,data:t6Tp+pYK2wC2Xb6v,iv:PJBvGuJuAoJqflyWwy2Btffo4eMgL4SYGzHCqxerj64=,tag:5IAj9xSiA3nWLBATo80JNw==,type:str]
sops:
    age:
        - recipient: age1ygxhg6wss8r0vm83cc557x9cxlx24m74ma4xh26lwspw7v0lgvzq5lddn0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycDhMN21TTTlpMmVtVmtK
            SU1Hc2dBUVA4ai9WQS9zSEpVRVlFTVFJa1VFCldiSnJvVmZadmRTblBCUTJJR2Zx
            TE16YlRhZnpOSXdkNWppYkQ1T1MxSE0KLS0tIDdiU0pzSGJZcUZwcjkyRXpWSktw
            dVNpR0E2UDJ6SjE5MnZGeUtMeDZUZmsKo0uEskdPrBhUEik6OtgigiCZdd2LGmAh
            tJyV5/wOIT6BGKfxLU/kg4r+XkgGOJ5rfSXg9NWoL6jNYR0Pg851RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T21:04:36Z"
    mac: ENC[AES256_GCM,data:+vdfpOrSrydvkeAuHXNYsguW0chYYbUT0h28LrMEyrNWTmXorKJulqvV4FyfvwVywi1OhmR+4U8j9MbQWdcK77jJZC98QRbmVr2Z0AR4c9ODGGKr6uzQ0lQL2TMmDt8WVwpGnMif3ODfEVdxA/8fT/EkcrG1DBeeWujPDUekSmg=,iv:00ZQRgSwf8L8m5HUXr0phev6fC3VDzp6LT5uwiE3vp4=,tag:oM3saAyNMvOAbbX4YIy1Sw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:88sgaNJNqewaHPlHUVQPp46xU1qAqKz7W9WYMbMIWZ/g/Xtkb5TvQNJsnNIRLkQyCAQLZGFSnsgddEslqMWDfocqI5SUPdsxlzEmKg+TXkf9NItsjpIFvg==,iv:kWeHpkxOOv+duSeRhXSZWX7NMLipJNTPPjpORbgKC3Y=,tag:4kWEwMBi96Gt8JklRWyuUQ==,type:str]
    AUTH_COOKIE_SECRET: ENC[AES256_GCM,data:mbSkAzvTScOtRA==,iv:bmJ17rBPvBbKqmK0zRXpc1EzVYFGMee223uWR0WUQLE=,tag:9NZgYS9QjzejSra9prLcqA==,type:str]
sops:
    age:
        - recipient: age1ygxhg6wss8r0vm83cc557x9cxlx24m74ma4xh26lwspw7v0lgvzq5lddn0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycDhMN21TTTlpMmVtVmtK
            SU1Hc2dBUVA4ai9WQS9zSEpVRVlFTVFJa1VFCldiSnJvVmZadmRTblBCUTJJR2Zx
            TE16YlRhZnpOSXdkNWppYkQ1T1MxSE0KLS0tIDdiU0pzSGJZcUZwcjkyRXpWSktw
            dVNpR0E2UDJ6SjE5MnZGeUtMeDZUZmsKo0uEskdPrBhUEik6OtgigiCZdd2LGmAh
            tJyV5/wOIT6BGKfxLU/kg4r+XkgGOJ5rfSXg9NWoL6jNYR0Pg851RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T21:04:36Z"
    mac: ENC[AES256_GCM,data:+vdfpOrSrydvkeAuHXNYsguW0chYYbUT0h28LrMEyrNWTmXorKJulqvV4FyfvwVywi1OhmR+4U8j9MbQWdcK77jJZC98QRbmVr2Z0AR4c9ODGGKr6uzQ0lQL2TMmDt8WVwpGnMif3ODfEVdxA/8fT/EkcrG1DBeeWujPDUekSmg=,iv:00ZQRgSwf8L8m5HUXr0phev6fC3VDzp6LT5uwiE3vp4=,tag:oM3saAyNMvOAbbX4YIy1Sw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
