apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: desktop
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portal.example.invalid`) && PathPrefix(`/api`)
      kind: Rule
      priority: 100
      services:
        - name: desktop
          port: 3000
    - match: Host(`portal.example.invalid`) && PathPrefix(`/`)
      kind: Rule
      priority: 1
      services:
        - name: desktop
          port: 4000
  tls:
    secretName: portal-tls-placeholder
