[versions]
#region Build & Kotlin
agp = "8.13.1"
kotlin = "2.2.21"
compose-multiplatform = "1.9.3"
kotlinx-coroutine = "1.10.2"

#region AndroidX & Compose
androidx-activityCompose = "1.12.0"
androidx-ui-tooling = "1.9.5"
androidx-compose-bom = "2025.11.01"
android-desugarJdkLibs = "2.1.5"
androidx-core-bundle = "1.1.0-alpha03"
compose-material3 = "1.10.0-alpha05"
compose-material-icons-extended = "1.7.3"
kotlinx-collections-immutable = "0.3.8"

#region Navigation & Lifecycle
navigationCompose = "2.9.1"
lifecycleCompose = "2.9.6"

#region Networking & Image Loading
ktor = "3.3.2"
coil = "3.3.0"

#region Dependency Injection
koin = "4.1.1"

#region Typography
compose-ui-text-google-fonts = "1.9.5"

#region Kotlinx Serialization
kotlinx-serialization-json = "1.9.0"
kotlinx-datetime = "0.7.1"
jetbrains-savedstate = "1.3.6"

#region Testing
kotlinStdlib = "2.2.21"
kotlinTest = "2.2.21"
runner = "1.7.0"
core = "1.7.0"
junit = "1.3.0"
junit-platform-launcher = "6.0.1"
junit5 = "6.0.1"
mockk = "1.14.6"
kotest = "6.0.5"
konsist = "0.17.3"

#region Code Quality
spotless = "8.1.0"

#region Database
room = "2.8.4"
sqlite = "2.6.2"
ksp = "2.2.21-2.0.4"

[libraries]
#region AndroidX & Compose UI
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activityCompose" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidx-ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidx-ui-tooling" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "android-desugarJdkLibs" }

#region Jetbrains Compose
jetbrains-compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "compose-multiplatform" }
jetbrains-compose-ui-tooling-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "compose-multiplatform" }
jetbrains-compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose-multiplatform" }
jetbrains-compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose-material3" }
jetbrains-compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose-multiplatform" }
jetbrains-compose-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleCompose" }
jetbrains-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycleCompose" }
jetbrains-lifecycle-viewmodel-savedstate = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycleCompose" }
jetbrains-savedstate = { group = "org.jetbrains.androidx.savedstate", name = "savedstate", version.ref = "jetbrains-savedstate" }
jetbrains-bundle = { group = "org.jetbrains.androidx.core", name = "core-bundle", version.ref = "androidx-core-bundle" }
jetbrains-compose-material-icons-extended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version.ref = "compose-material-icons-extended" }

#region Navigation & Lifecycle
jetbrains-navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
jetbrains-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleCompose" }

#region Networking (Ktor)
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }

#region Image Loading (Coil)
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-ktor = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }

#region Dependency Injection (Koin)
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
koin-androidx-navigation = { group = "io.insert-koin", name = "koin-androidx-navigation", version.ref = "koin" }
koin-core-viewmodel = { group = "io.insert-koin", name = "koin-core-viewmodel", version.ref = "koin" }

#region Kotlinx Serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }

#region Kotlin Related
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutine" }

#region Typography (Google Fonts)
compose-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "compose-ui-text-google-fonts" }

#region Testing
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTest" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
konsist = { group = "com.lemonappdev", name = "konsist", version.ref = "konsist" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform-launcher" }

#region Database
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-sqlite-wrapper = { module = "androidx.room:room-sqlite-wrapper", version.ref = "room" }

#region Code Quality
spotless-gradlePlugin = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }

#region Convention Plugin Dependencies
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradlePlugin = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "compose-multiplatform" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }

[bundles]
compose-ui = [
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview"
]

ktor-common = [
    "ktor-client-core",
    "ktor-client-content-negotiation",
    "ktor-serialization-kotlinx-json"
]

coil = [
    "coil-compose",
    "coil-network-ktor"
]

koin = [
    "koin-core",
    "koin-compose-viewmodel"
]

navigation-lifecycle = [
    "jetbrains-navigation-compose",
    "jetbrains-lifecycle-runtime-compose"
]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
androidLint = { id = "com.android.lint", version.ref = "agp" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-room = { id = "androidx.room", version.ref = "room" }

# Convention Plugins
eloquia-android-application = { id = "eloquia.android.application" }
eloquia-android-application-compose = { id = "eloquia.android.application.compose" }
eloquia-cmp-application = { id = "eloquia.cmp.application" }
eloquia-cmp-library = { id = "eloquia.cmp.library" }
eloquia-cmp-feature = { id = "eloquia.cmp.feature" }
eloquia-kmp-library = { id = "eloquia.kmp.library" }
eloquia-kmp-application = { id = "eloquia.kmp.application" }
eloquia-architecture-tests = { id = "eloquia.architecture.tests" }
eloquia-kmp-compose = { id = "eloquia.kmp.compose" }
eloquia-android-compose = { id = "eloquia.android.compose" }
eloquia-ios-framework = { id = "eloquia.ios.framework" }
eloquia-kmp-networking = { id = "eloquia.kmp.networking" }
eloquia-kmp-di = { id = "eloquia.kmp.di" }
eloquia-kmp-room = { id = "eloquia.kmp.room" }
eloquia-kmp-library-no-desktop = { id = "eloquia.kmp.library.no-desktop" }
