apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
  labels:
    app: backend-migrate
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: backend-migrate
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      restartPolicy: Never
      containers:
        - name: atlas
          image: ghcr.io/stutter-journal/eloquia-backend-migrate:main-00000000000000-0000000 # {"$imagepolicy": "flux-system:eloquia-backend-migrate"}
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: backend-secrets
