- op: replace
  path: /spec/routes/0/match
  value: Host(`portal.staging.eloquia.bajaga.net`) && PathPrefix(`/api`)
- op: replace
  path: /spec/routes/1/match
  value: Host(`portal.staging.eloquia.bajaga.net`) && PathPrefix(`/`)
- op: replace
  path: /spec/tls/secretName
  value: eloquia-staging-portal-tls
