- op: replace
  path: /spec/routes/0/match
  value: Host(`app.eloquia.test`) && PathPrefix(`/api`)
- op: replace
  path: /spec/routes/1/match
  value: Host(`app.eloquia.test`) && PathPrefix(`/`)
- op: replace
  path: /spec/tls/secretName
  value: eloquia-app-tls
