apiVersion: v1
kind: Secret
metadata:
  name: ghcr-credentials
  namespace: flux-system
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ".*"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "eloquia-.*"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: REPLACE_ME
