apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: eloquia-backend
  namespace: flux-system
spec:
  image: ghcr.io/stutter-journal/eloquia-backend
  interval: 1m0s
  secretRef:
    name: ghcr-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: eloquia-backend-migrate
  namespace: flux-system
spec:
  image: ghcr.io/stutter-journal/eloquia-backend-migrate
  interval: 1m0s
  secretRef:
    name: ghcr-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: eloquia-desktop
  namespace: flux-system
spec:
  image: ghcr.io/stutter-journal/eloquia-desktop
  interval: 1m0s
  secretRef:
    name: ghcr-credentials
