apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: image-automation
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./deploy/flux-image-automation
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
