apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system
- infrastructure.yaml
- apps.yaml
- infrastructure-staging.yaml
- apps-staging.yaml
- infrastructure-production.yaml
- apps-production.yaml
