apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eloquia-production
resources:
  - ../../base
patches:
  - target:
      kind: Namespace
    path: patches/namespace-name.yaml
