apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bajaga-secrets # <to be changed later if necessary>
    kind: ClusterSecretStore
  target:
    name: postgres-auth
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: eloquia/staging/postgres/password
    - secretKey: postgres-password
      remoteRef:
        key: eloquia/staging/postgres/postgres-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bajaga-secrets # <to be changed later if necessary>
    kind: ClusterSecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: eloquia/staging/backend/database_url
    - secretKey: AUTH_COOKIE_SECRET
      remoteRef:
        key: eloquia/staging/backend/auth_cookie_secret
