apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Hgf7wZ4ayTHxR2Ma,iv:MDAlI6aS70kxERRxNdUATfUuJ7iOxK83LhVFM+xfZjA=,tag:w5ORn/6SKxgRjhkdMzXoSg==,type:str]
    postgres-password: ENC[AES256_GCM,data:ERj/ddJuOwUYoZls,iv:3bgrn6dQPadKX7EnOHvf6jzKX3SbYJha5gBqxZeJSsM=,tag:LRyzmMqjG2nBFwOeR5vZ6A==,type:str]
sops:
    age:
        - recipient: age1ygxhg6wss8r0vm83cc557x9cxlx24m74ma4xh26lwspw7v0lgvzq5lddn0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZzBYcSsra3hxTjNMcTdL
            TlFwdms4UlJwK0pjMjcva0pubEtBTnRUcDB3CjJmM3J5a1FXQkxnYSsrWmVielhS
            MEhjMElLMWQyVERKNUoyWlhmTVF3Tm8KLS0tIHpPYTJqQmRybFZpVDBoVkgrZUx0
            aER4eE1ZTnZkL2NpTzVneHVqekxTWmMKG+kvahlW+HPBK1EspAVcPubL38CSwLQi
            YDmHvvYDnWpBHxRS2Yt0qu0fze7b16+D3pqwZrMB+Y9wn7YYidT4og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T21:04:33Z"
    mac: ENC[AES256_GCM,data:uaAQWYbn1J2YhtCX0bV9gAEYHsRS6VnS+HfgsRJcJbNl31JkoIsj4YMDip6vlMTIil0hIgvx/7Xpza0URl7gi/MTv3QGgoSib5+UqUI7wijXmsXiMVheH56DKzuPZTfrtshU9t0XCTsbHfLimSr5IIYvR3nhusxPZK3njSmN58g=,iv:xghfKu8N897LKoPd08oStQzCFZir7d2CzDboIiiJIQE=,tag:ULoVpKdOA7TTg13DSC0G3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:pDsTfYzUgSSuXa74DOAkZvAoI1M23V+hyBmOUYbOBpYepSsSvmkc7vqz1lUxT14WFLcvpoktlJQaadfYkd2zbs8/eN7e06Uyuu8Xz5sxd4m30Sc1lsVzqA==,iv:AH6+wX4IgRUih05Zw2IuRqu1P7ex4LaXiO2qa2ywwXw=,tag:1ZedCMRZbR5mBh+1WRy9gw==,type:str]
    AUTH_COOKIE_SECRET: ENC[AES256_GCM,data:I7B4iKcC6SuPXw==,iv:Ll4KcMTywXuZWngCH2Q/f7EhsAn1yY1ip+SEuzzmllA=,tag:+ivH62Oe7Y1rR25VJ3GYqg==,type:str]
sops:
    age:
        - recipient: age1ygxhg6wss8r0vm83cc557x9cxlx24m74ma4xh26lwspw7v0lgvzq5lddn0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZzBYcSsra3hxTjNMcTdL
            TlFwdms4UlJwK0pjMjcva0pubEtBTnRUcDB3CjJmM3J5a1FXQkxnYSsrWmVielhS
            MEhjMElLMWQyVERKNUoyWlhmTVF3Tm8KLS0tIHpPYTJqQmRybFZpVDBoVkgrZUx0
            aER4eE1ZTnZkL2NpTzVneHVqekxTWmMKG+kvahlW+HPBK1EspAVcPubL38CSwLQi
            YDmHvvYDnWpBHxRS2Yt0qu0fze7b16+D3pqwZrMB+Y9wn7YYidT4og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T21:04:33Z"
    mac: ENC[AES256_GCM,data:uaAQWYbn1J2YhtCX0bV9gAEYHsRS6VnS+HfgsRJcJbNl31JkoIsj4YMDip6vlMTIil0hIgvx/7Xpza0URl7gi/MTv3QGgoSib5+UqUI7wijXmsXiMVheH56DKzuPZTfrtshU9t0XCTsbHfLimSr5IIYvR3nhusxPZK3njSmN58g=,iv:xghfKu8N897LKoPd08oStQzCFZir7d2CzDboIiiJIQE=,tag:ULoVpKdOA7TTg13DSC0G3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
